### ISSUE TITLE
HU-Editor - Refresh after HU-changing process not working properly

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-api-legacy#1007]
### Is this a bug or feature request?
Bug
### What is the current behavior?

I believe it's a more general problem, but here is one manifestation:
* Process `WEBUI_M_HU_MoveTUsToDirectWarehouse` ("Materialentnahme (partial)")
* filter for a particular barcode (=> i.e. selet a LU)
* take one one TU
* **NOK** the LU is not updated properly. 
* I played with calling
  * `invalidateView();`
  * `getView().notifyRecordsChanged(ImmutableSet.of(TableRecordReference.of(topLevelHU)));`
  * either it's unchanged (not updated at all) or it's empty.
* i believe the current problem is that the invalidation code we have clears 'T_WEBUI_ViewSelection'..
* i think (also talked with teo about it) we 
   * either need to create a new selection with the "old"/current filters
   * or apply HUs that were changed to the "old"/current filters add/remove stuff as required

**Comment by metas-lc** [comment]
IT
0. config: de.metas.handlingunits.client.terminal.inventory.model.InventoryHUEditorModel#DirectMove_Warehouse_ID
1. receive an LU with 5 TUs (aggregated)
2. go to Handling Units Editor and filter for the LU or just select it
3. run materialentnahme (partial) action, on qty TU set 2. Start
=> LU has now 3 TUs OK
=> the new TUs are also created (if you have filter applied you have to clear it to find them) OK
=> 2 movements created to DirectMove_Warehouse OK
.
4. receive 2 LUs, each with 1 TU. Use transform to move a TU on the other LU - so you have an LU with 2 unaggregated TUs
5.  go to Handling Units Editor and select that HU
6. run materialentnahme (partial) action, on qty TU set 1. Start
=> LU updated OK
=> the old TU was moved out from the LU (after refreshing the page) OK
=> 2 movements created to DirectMove_Warehouse OK
.
7. use materialentnahme (partial) o a filtered LU
=> lu updates
8. remove the filter, immediately use materialentnahme (partial) on a selected LU (or filter for it)
=> lu does not update (need to refresh the page) NOK

**Comment by metas-lc** [comment]
note: HU Status is still Active when you use materialentnahme. So you will still see them in HU Editor. Please check if this is ok, or if hu status hall be destroyed

**Comment by teosarca** [comment]
i can also confirm that behaviour.
@metas-mk  @metas-ts  wdyt, is it OK?

**Comment by teosarca** [comment]
closing legacy issue
