### ISSUE TITLE
API: Internal Use Action in Handling Unit Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api-legacy#497]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Internal Use Action is not working in WebUI Handling Unit Editor.
#### Which are the steps to reproduce?
Open HU Editor, select an HU and Press "Materialentnahme"
### What is the expected or desired behavior?
Shall work. The Process ID 540541.

![image](https://user-images.githubusercontent.com/13365687/28156469-27910610-67b3-11e7-9621-b1a5a6244618.png)

![image](https://user-images.githubusercontent.com/13365687/28156459-1d59acba-67b3-11e7-8868-bc43c24ec3f8.png)

**Comment by teosarca** [comment]
closing legacy issue
