### ISSUE TITLE
Picking Window: pick only selected detail rows

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api-legacy#558]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when selecting a subrecord in Picking Terminal window, then you cannot pick because of error.
#### Which are the steps to reproduce?
Open, select subrecord and see.
### What is the expected or desired behavior?
Shall work.

![image](https://user-images.githubusercontent.com/13365687/29866591-1fd65dda-8d79-11e7-9480-6874b5980a8b.png)

**Comment by teosarca** [comment]
closing legacy issue
