### ISSUE TITLE
Handling Unit Editor Result refresh after Internal Usage missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api-legacy#718]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In Handling Unit Editor, when filtering a product and warehouse and the result has more than 1 page. Select all from the page. Do Internal Usage. The result shows an empty page.
#### Which are the steps to reproduce?
Try whats described above.
### What is the expected or desired behavior?
Should show filtering criteria reloaded/ refreshed. An empty page does not make sense.

![image](https://user-images.githubusercontent.com/13365687/33594239-6ed3c40c-d993-11e7-9e94-495ea81cd9ae.png)

**Comment by teosarca** [comment]
closing legacy issue
