### ISSUE TITLE
Only 1 new HU shall be created when using "Take out and add to new HU" 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-api-legacy#884]
### Is this a bug or feature request?
Bug
### What is the current behavior?
"Take out and add to new HU" action in picking clearing:
When 2 products w/ different UOMs are taken out and put into new HU, then 2 new HUs are created.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
All HUs shall be put into the same new HU.

**Comment by teosarca** [comment]
closing legacy issue
