### ISSUE TITLE
Select all Action Delete

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-api-legacy#889]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to select multiple/ all rows in a grid view and to call the action "Delete".
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please provide the "delete" action so that it can be used in grid view with multiple selections.

![image](https://user-images.githubusercontent.com/13365687/36978001-5dbf0de8-2083-11e8-9ad8-c44956cad37a.png)

**Comment by teosarca** [comment]
closing legacy issue
