### ISSUE TITLE
Picking terminal: sometimes picking slot vanishes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-api-legacy#925]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* select a picking line 
* select an empty picking slot
* pick something
=> sometimes picking slot vanishes
I've observed it's happening when you shipment schedules are from different bpartners and for some reason the BP of first shipment schedule was used, instead of using the BP of current selected line.

### What is the expected or desired behavior?
shall work nicely

**Comment by metas-lc** [comment]
IT
1. created 2 sales orders with 2 different bpartners, same product
2. went to picking slot and selected the product - pick
3. selected a line on left side, slot 101, picked 1 HU 
=> now this slot has a bpartner set (the one from your selected line)
4. select the other line
=> slot 101 is visible and doesn't have bpartner set. i think NOK (?)
5. select slot 101 and pick something there
=> now the picking slot is gone NOK (i think it shall not be there in the first place. or?)

**Comment by teosarca** [comment]
closing legacy issue
